languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Congo"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"
