# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the README for more details about each of these parameters.

[homepage]
  layout = "page" # valid options: page, profile, custom
  showList = false
  listSections = ["blog"]

[article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true

[list]
  groupByYear = true

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
