[build]
  command = "cd exampleSite && hugo --gc --minify -b $URL"
  publish = "exampleSite/public"

[build.environment]
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"
TZ = "Australia/Melbourne"

[context.production.environment]
HUGO_VERSION = "0.89.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd exampleSite && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.89.3"

[context.branch-deploy]
command = "cd exampleSite && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.89.3"
