languageCode = "en-AU"
languageName = "English (Australia)"
languageDirection = "ltr"
weight = 1

title = "Congo"
copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "Congo"
  image = "img/author.jpg"
  headline = "Not your ordinary theme!"
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { x-twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
