blank_issues_enabled: true
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/jpanther/congo/discussions
    about: Request and discuss enhancements using GitHub Discussions
  - name: ğŸ™‹â€â™€ï¸ Question
    url: https://github.com/jpanther/congo/discussions
    about: Please ask and answer general questions using GitHub Discussions
